<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/03/30 17:14:03

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=buildgreen',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
