<?php

/**
 * BuildgreenCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BuildgreenCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BuildgreenCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BuildgreenCategory');
    }
}