<?php

/**
 * BuildgreenCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BuildgreenCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BuildgreenCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BuildgreenCategory');
    }
      public function getMenuTree()
      {

        $q = $this->createQuery('g')
          ->orderBy('root_id')
          ->addOrderBy('lft')
          ->where('root_id');;

        return $q->execute(array(),  Doctrine_Core::HYDRATE_ARRAY_HIERARCHY);
      }

}
