<?php

/**
 * BuildgreenArticleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BuildgreenArticleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BuildgreenArticleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BuildgreenArticle');
    }
}