generator:
  class: sfDoctrineGenerator
  param:
    model_class:           BuildgreenCategory
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          buildgreen_category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        hide: [root_id, lft, rgt, level]
        title: Category Management
        max_per_page: 10
      filter:  ~
      form:    ~
      edit:
        title: Editing Category "%%title%%"
      new:
        title: New Category
