generator:
  class: sfDoctrineGenerator
  param:
    model_class:           BuildgreenArticle
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          buildgreen_article
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        hide: [body]
        title: Articles Management
        max_per_page: 10
      filter:  ~
      form:    ~
      edit:
        title: Editing Article "%%id%%"
      new:
        title: New Article
