BuildgreenCategory:
  actAs:
    NestedSet:
      hasManyRoots: true
      rootColumnName: root_id
  columns:
    title: { type: string(255), notnull: true, unique: true }
    is_visible: { type: boolean, notnull: true, default: 1 }
    order_n: { type: integer, notnull: true }
    img_url:  { type: string(255), notnull: true }

BuildgreenArticle:
  actAs: { Timestampable: ~ }
  columns:
    category_id:  { type: integer, notnull: true }
    body: { type: string(4000), notnull: true }
    is_visible: { type: boolean, notnull: true, default: 1 }
  relations:
    BuildgreenCategory: { onDelete: CASCADE, local: category_id, foreign: id, foreignAlias: BuildgreenArticle }
